apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    purpose: nginx-demo-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      purpose: nginx-demo-deployment
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: service-lb-demo
        project: roboshop
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.deployment.imageVersion }}
        # - name: nginx
        #   image: nginx:stable-perl
